-- Create study_guide_pages table for storing page-by-page descriptions
CREATE TABLE IF NOT EXISTS study_guide_pages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  study_guide_id UUID NOT NULL REFERENCES study_guides(id) ON DELETE CASCADE,
  page_number INTEGER NOT NULL,
  page_title TEXT,
  page_content TEXT NOT NULL,
  key_concepts TEXT[],
  difficulty_level TEXT CHECK (difficulty_level IN ('easy', 'medium', 'hard')),
  prerequisites TEXT[],
  learning_objectives TEXT[],
  original_content TEXT, -- Store original PDF page content for reference
  created_at TIMESTAMPTZ DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ DEFAULT timezone('utc', now()),
  
  -- Ensure unique page numbers per study guide
  UNIQUE(study_guide_id, page_number)
);

-- Create indexes for better query performance
CREATE INDEX idx_study_guide_pages_study_guide_id ON study_guide_pages(study_guide_id);
CREATE INDEX idx_study_guide_pages_page_number ON study_guide_pages(study_guide_id, page_number);

-- Add metadata columns to study_guides table
ALTER TABLE study_guides 
ADD COLUMN IF NOT EXISTS document_title TEXT,
ADD COLUMN IF NOT EXISTS total_pages INTEGER,
ADD COLUMN IF NOT EXISTS overall_summary TEXT,
ADD COLUMN IF NOT EXISTS generation_method TEXT DEFAULT 'legacy';

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_study_guide_pages_updated_at 
BEFORE UPDATE ON study_guide_pages 
FOR EACH ROW 
EXECUTE FUNCTION update_updated_at_column();

-- Add comment for documentation
COMMENT ON TABLE study_guide_pages IS 'Stores page-by-page study guide descriptions generated by Gemini AI';
COMMENT ON COLUMN study_guide_pages.page_content IS 'Customized explanation for this specific page based on user knowledge level';
COMMENT ON COLUMN study_guide_pages.key_concepts IS 'Array of key concepts covered in this page';
COMMENT ON COLUMN study_guide_pages.difficulty_level IS 'Estimated difficulty level of the page content';
COMMENT ON COLUMN study_guide_pages.prerequisites IS 'Concepts that should be understood before this page';
COMMENT ON COLUMN study_guide_pages.learning_objectives IS 'What the student should learn from this page';
COMMENT ON COLUMN study_guide_pages.original_content IS 'Original PDF page text for reference';
COMMENT ON COLUMN study_guides.generation_method IS 'Method used to generate the guide: legacy (single content) or pages (page-by-page)';